# Generated by Django 5.1.6 on 2025-08-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquorapp', '0002_alter_shopmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopmodel',
            name='email',
        ),
    ]
