# Generated by Django 5.1.4 on 2025-08-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorapp', '0003_remove_shopmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
