# Generated by Django 5.1.4 on 2025-09-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorapp', '0005_alter_ordermodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='total',
            field=models.IntegerField(),
        ),
    ]
