# Generated by Django 5.1.4 on 2025-09-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorapp', '0006_alter_ordermodel_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
