# Generated by Django 5.1.4 on 2025-09-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquorapp', '0007_alter_ordermodel_quantity_alter_ordermodel_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerModel',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='customer',
            new_name='user',
        ),
    ]
