# Generated by Django 5.2.6 on 2025-09-18 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorapp', '0008_delete_customermodel_rename_customer_ordermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liquorapp.shopmodel'),
        ),
    ]
