# Generated by Django 5.2.6 on 2025-09-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquorapp', '0010_rename_ordermodel_cartmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquorapp.cartmodel')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_sent', to=settings.AUTH_USER_MODEL)),
                ('shopkeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_recv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
